import { FlatCompat } from "@eslint/eslintrc";
import js from "@eslint/js";
import tsParser from "@typescript-eslint/parser";
import unicorn from "eslint-plugin-unicorn";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const compat = new FlatCompat({
	baseDirectory: __dirname,
	recommendedConfig: js.configs.recommended,
});

export default [
	{
		ignores: ["distribution/**", "coverage/**", "node_modules/**"],
	},
	...compat.extends(
		"eslint:recommended",
		"plugin:@typescript-eslint/eslint-recommended",
		"plugin:@typescript-eslint/recommended-requiring-type-checking",
		"plugin:@typescript-eslint/recommended",
		"plugin:import/errors",
		"plugin:import/typescript",
		"plugin:import/warnings",
		"plugin:prettier/recommended",
		"plugin:promise/recommended",
		"plugin:sonarjs/recommended-legacy",
		"prettier",
	),
	unicorn.configs.recommended,
	{
		languageOptions: {
			parser: tsParser,
			parserOptions: {
				project: "./tsconfig.json",
				extraFileExtensions: [".json"],
			},
		},
		plugins: {
			"simple-import-sort": (await import("eslint-plugin-simple-import-sort")).default,
			"sort-keys-fix": (await import("eslint-plugin-sort-keys-fix")).default,
			"unused-imports": (await import("eslint-plugin-unused-imports")).default,
		},
		rules: {
			"@typescript-eslint/ban-ts-comment": "off",
			"@typescript-eslint/ban-types": "off",
			"@typescript-eslint/explicit-module-boundary-types": "off",
			"@typescript-eslint/naming-convention": "off",
			"@typescript-eslint/no-empty-function": "off",
			"@typescript-eslint/no-empty-interface": "off",
			"@typescript-eslint/no-explicit-any": "off",
			"@typescript-eslint/no-misused-promises": "off",
			"@typescript-eslint/no-non-null-asserted-optional-chain": "off",
			"@typescript-eslint/no-non-null-assertion": "off",
			"@typescript-eslint/no-unsafe-argument": "off",
			"@typescript-eslint/no-unsafe-assignment": "off",
			"@typescript-eslint/no-unsafe-call": "off",
			"@typescript-eslint/no-unsafe-member-access": "off",
			"@typescript-eslint/no-unsafe-return": "off",
			"@typescript-eslint/no-unused-vars": "off",
			"@typescript-eslint/no-var-requires": "off",
			"@typescript-eslint/require-await": "off",
			"@typescript-eslint/restrict-plus-operands": "off",
			"@typescript-eslint/restrict-template-expressions": "off",
			"arrow-body-style": ["error", "as-needed"],
			curly: "error",
			"import/default": "error",
			"import/export": "warn",
			"import/exports-last": "warn",
			"import/extensions": ["warn", "always"],
			"import/first": "error",
			"import/group-exports": "off",
			"import/namespace": "error",
			"import/no-absolute-path": "error",
			"import/no-anonymous-default-export": "error",
			"import/no-cycle": "warn",
			"import/no-deprecated": "error",
			"import/no-duplicates": "error",
			"import/no-dynamic-require": "off",
			"import/no-extraneous-dependencies": "error",
			"import/no-mutable-exports": "error",
			"import/no-namespace": "error",
			"import/no-restricted-paths": "error",
			"import/no-self-import": "error",
			"import/no-unresolved": "off",
			"import/no-unused-modules": "error",
			"import/no-useless-path-segments": "error",
			"import/no-webpack-loader-syntax": "error",
			"import/order": "error",
			"no-async-promise-executor": "off",
			"no-nested-ternary": "error",
			"no-prototype-builtins": "off",
			"no-unneeded-ternary": "error",
			"no-unused-expressions": "off",
			"no-unused-vars": "off",
			"prefer-const": [
				"error",
				{
					destructuring: "all",
				},
			],
			"prettier/prettier": [
				"off",
				{
					endOfLine: "auto",
				},
			],
			"promise/param-names": "error",
			// crashes ts-eslint's type resolution on `Networks["ark.devnet"]`-style element
			// access inside test assertions (TypeScript Debug Failure in eslint-plugin-sonarjs)
			"sonarjs/assertions-in-tests": "off",
			"simple-import-sort/exports": "error",
			"simple-import-sort/imports": "error",
			"sonarjs/cognitive-complexity": "warn",
			"sonarjs/no-all-duplicated-branches": "error",
			"sonarjs/no-collapsible-if": "error",
			"sonarjs/no-duplicate-string": "off",
			"sonarjs/no-identical-expressions": "error",
			"sonarjs/no-identical-functions": "error",
			"sonarjs/no-redundant-jump": "error",
			"sonarjs/no-small-switch": "error",
			"sonarjs/no-use-of-empty-return-value": "error",
			"sort-keys-fix/sort-keys-fix": ["error", "asc", { caseSensitive: true }],
			"unicorn/consistent-destructuring": "warn",
			"unicorn/consistent-function-scoping": "warn",
			"unicorn/error-message": "warn",
			"unicorn/explicit-length-check": "warn",
			"unicorn/filename-case": "warn",
			"unicorn/import-style": "warn",
			"unicorn/no-abusive-eslint-disable": "warn",
			"unicorn/no-array-callback-reference": "warn",
			"unicorn/no-array-for-each": "warn",
			"unicorn/no-array-method-this-argument": "warn",
			"unicorn/no-array-reduce": "warn",
			"unicorn/no-await-expression-member": "warn",
			"unicorn/no-new-array": "warn",
			"unicorn/no-null": "warn",
			"unicorn/no-object-as-default-parameter": "warn",
			"unicorn/no-useless-undefined": "warn",
			"unicorn/prefer-array-some": "warn",
			"unicorn/prefer-at": "warn",
			"unicorn/prefer-module": "warn",
			"unicorn/prefer-node-protocol": "off",
			"unicorn/prefer-number-properties": "warn",
			"unicorn/prefer-prototype-methods": "warn",
			"unicorn/prefer-spread": "warn",
			"unicorn/prefer-string-slice": "warn",
			"unicorn/prefer-ternary": "off",
			"unicorn/prefer-top-level-await": "warn",
			"unicorn/prevent-abbreviations": "warn",
			"unused-imports/no-unused-imports": "warn",
		},
	},
];
