name: Publish (Master)

on:
    push:
        branches:
            - "master"

permissions:
    contents: read

jobs:
    publish:
        if: "contains(github.event.head_commit.message, 'release:')"

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.9.1]

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

             - uses: pnpm/action-setup@v2
              with:
                  version: 6.24.4

            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Publish to NPM
              run: npm publish --access=public --publish-branch=main
              env:
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
