name: Publish (Master)

on:
    push:
        branches:
            - "master"
            - "feat/mainsail"

permissions:
    id-token: write # OIDC
    contents: read

jobs:
    master:
        if: contains(github.event.head_commit.message, 'release:') && github.ref == 'refs/heads/master'

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 22

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/
                  cache: pnpm

            # Ensure npm 11.5.1 or later is installed for Trusted publishing
            - name: Update npm
              run: npm install -g npm@11

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Publish to NPM
              run: npm publish --access=public --publish-branch=master

    mainsail:
        if: contains(github.event.head_commit.message, 'release:') && github.ref == 'refs/heads/feat/mainsail'

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 22

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/
                  cache: pnpm

            # Ensure npm 11.5.1 or later is installed for Trusted publishing
            - name: Update npm
              run: npm install -g npm@11

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build
              run: pnpm build

            - name: Publish to NPM
              run: npm publish --access=public --publish-branch=feat/mainsail --tag=next
