name: Test
on:
    push:
        branches:
            - master
            - develop
    pull_request:
        types:
            - ready_for_review
            - synchronize
            - opened
jobs:
    app:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version:
                    - 16.9.1
        concurrency:
            group: ${{ github.head_ref }}-test-app
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: pnpm/action-setup@v2
              with:
                  version: 6.24.4
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Install (pnpm)
              run: pnpm install --frozen-lockfile
            - name: Test
              uses: nick-invision/retry@v2
              with:
                  timeout_minutes: 10
                  max_attempts: 1
                  command: node --expose-gc ./node_modules/jest/bin/jest.js
                      src/ --forceExit --maxWorkers=2 --logHeapUsage --watchAll=false --coverage
                      --collectCoverageFrom='["src/**/*.{js,jsx,ts,tsx}","!<rootDir>/distribution/*","!jest.setup.js","!src/**/*.models.{js,jsx,ts,tsx}","!src/**/*.test.ts"]'
                      --coverageThreshold='{"./src/":{"branches":100,"functions":100,"lines":100,"statements":100}}'
